#!/usr/bin/env python
"""Generate ablation-variant YAML configs from a dataset's base config.

Each variant is a deep copy of the base config with one module ablated:
  no_profile      -> profiles.enabled: false
  no_micro_sched  -> activities.enabled: false
  no_social       -> simulation.alpha: 0.0
  no_transport    -> road_network.enabled: false, rail_network.enabled: false
  no_feedback     -> reset manually-tuned hyperparameters to schema defaults

`simulation.output` is always rewritten so each variant's runs land in their
own namespaced file stem; everything else (tessellation/road/rail graph
caches, LLM/embedding/alignment caches, profiles.output) stays pointed at the
base config's shared paths, since none of these ablations change what those
caches key on.
"""
from __future__ import annotations

import argparse
import copy
from pathlib import Path
from typing import Any, Iterable

import yaml

AUTOGEN_HEADER = (
    "# AUTO-GENERATED by scripts/make_ablation_config.py --base {base} --variant {variant}\n"
    "# Do not hand-edit; regenerate instead.\n"
)

# "set" keys are dotted-path overrides. "unset" keys are dotted paths to delete
# (falls back to the Pydantic schema default / catalog default). Missing keys
# in "unset" are silently ignored so one variant definition works across
# datasets whose base configs don't all override the same fields.
VARIANTS: dict[str, dict[str, Any]] = {
    "no_profile": {"set": {"profiles.enabled": False}},
    "no_micro_sched": {"set": {"activities.enabled": False}},
    "no_social": {"set": {"simulation.alpha": 0.0}},
    "no_transport": {
        "set": {"road_network.enabled": False, "rail_network.enabled": False}
    },
    "no_feedback": {
        "set": {
            "diaries.motif_exploration_rate": 1.0,
            "diaries.location_count_sigma": 0.5,
            "schedule.temperature_beta_a": 2.0,
            "schedule.temperature_beta_b": 5.0,
            "schedule.alpha_beta_a": 2.0,
            "schedule.alpha_beta_b": 5.0,
            "activities.kappa": 1.0,
            "activities.temperature": 0.5,
            "profiles.work_from_home_probability": 0.05,
            "simulation.gravity_deterrence_exponent": -2.0,
        },
        "unset": ["diaries.max_one_location_diaries", "activities.durations"],
    },
}


def _set_nested(d: dict[str, Any], dotted_key: str, value: Any) -> None:
    parts = dotted_key.split(".")
    node = d
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = value


def _unset_nested(d: dict[str, Any], dotted_key: str) -> None:
    parts = dotted_key.split(".")
    node = d
    for part in parts[:-1]:
        if part not in node or not isinstance(node[part], dict):
            return
        node = node[part]
    node.pop(parts[-1], None)


def _stamp_variant_output(cfg: dict[str, Any], dataset: str, variant: str) -> None:
    cfg.setdefault("simulation", {})["output"] = (
        f"data/{dataset}/results/ablation/{dataset}_{variant}_trajectories.parquet"
    )


def apply_variant(base_cfg: dict[str, Any], dataset: str, variant: str) -> dict[str, Any]:
    if variant not in VARIANTS:
        raise ValueError(f"unknown variant {variant!r}; choices: {sorted(VARIANTS)}")
    cfg = copy.deepcopy(base_cfg)
    spec = VARIANTS[variant]
    for key, value in spec.get("set", {}).items():
        _set_nested(cfg, key, value)
    for key in spec.get("unset", []):
        _unset_nested(cfg, key)
    _stamp_variant_output(cfg, dataset, variant)
    return cfg


def _dump(cfg: dict[str, Any], base_path: str, variant: str) -> str:
    header = AUTOGEN_HEADER.format(base=base_path, variant=variant)
    return header + yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True)


def parse_args(argv: Iterable[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--base", required=True, help="Path to the base (full-model) YAML")
    parser.add_argument("--dataset", required=True, help="Dataset name, e.g. shanghai")
    parser.add_argument(
        "--variant",
        choices=sorted(VARIANTS),
        help="Single variant to generate. Omit with --all to generate every variant.",
    )
    parser.add_argument("--all", action="store_true", help="Generate all 5 variants")
    parser.add_argument(
        "--out-dir",
        default=None,
        help="Output directory. Defaults to configs/ablations/<dataset>/",
    )
    parser.add_argument("--dry-run", action="store_true", help="Print diff, write nothing")
    return parser.parse_args(argv)


def main(argv: Iterable[str] | None = None) -> None:
    args = parse_args(argv)
    if not args.all and not args.variant:
        raise SystemExit("pass --variant <name> or --all")
    variants = sorted(VARIANTS) if args.all else [args.variant]

    with open(args.base) as f:
        base_cfg = yaml.safe_load(f)

    out_dir = Path(args.out_dir or f"configs/ablations/{args.dataset}")

    for variant in variants:
        cfg = apply_variant(base_cfg, args.dataset, variant)
        text = _dump(cfg, args.base, variant)
        out_path = out_dir / f"{args.dataset}_{variant}.yaml"
        if args.dry_run:
            print(f"--- {out_path} ---")
            print(text)
        else:
            out_dir.mkdir(parents=True, exist_ok=True)
            out_path.write_text(text)
            print(f"wrote {out_path}")


if __name__ == "__main__":
    main()
