#!/usr/bin/env python3
"""One-off: regenerate all 45 ablation reports under the new RECAST-friends
network validation code (Phase 1 of the overnight plan). Regenerates
combos whose report predates this script (== predates the RECAST-friends
switch, since every report existing before tonight used the old raw
co-presence + sidecar-based synthetic graph). Does not touch simulation
data -- reuses existing trajectories. Resumable: skip a combo whose report
file's mtime is already newer than this script's own mtime (i.e. it was
already regenerated by a prior run of this same script tonight) -- avoids
redoing the ~15min-per-cold-cache yjmob combos after an interrupted run.
"""
import json
import os
import subprocess
import sys
import time

MANIFEST = "data/ablation_logs/manifest.jsonl"
VARIANTS = {"full", "no_profile", "no_micro_sched", "no_social", "no_transport"}
DATASETS = {"shanghai", "yjmob", "yjmob2"}
# Fixed cutoff (not this script's own mtime -- editing the script bumps its
# mtime past already-done reports, silently breaking the skip check). This
# is network_validation.py's mtime when the RECAST-friends rewrite (Phase 1)
# was finished tonight -- any report newer than this was generated under the
# new code.
RECAST_FRIENDS_CUTOFF = 1789605710

rows = [json.loads(line) for line in open(MANIFEST)]
all_targets = [r for r in rows if r["dataset"] in DATASETS and r["variant"] in VARIANTS and r.get("report_json_path")]
all_targets.sort(key=lambda r: {"shanghai": 0, "yjmob2": 1, "yjmob": 2}.get(r["dataset"], 9))

targets = []
skipped = 0
for r in all_targets:
    path = r["report_json_path"]
    if os.path.exists(path) and os.path.getmtime(path) > RECAST_FRIENDS_CUTOFF:
        skipped += 1
        continue
    targets.append(r)

print(f"=== RECAST-friends ablation backfill: {len(targets)} combos to do, {skipped} already fresh ===", flush=True)
for i, r in enumerate(targets, 1):
    tag = f"{r['dataset']}_{r['variant']}_run{r['run_index']}"
    t0 = time.time()
    print(f"--- [{i}/{len(targets)}] {tag} ---", flush=True)
    result = subprocess.run(
        [
            "uv", "run", "citybehavex", "report",
            "--config", r["config_path"],
            "--synthetic", r["trajectories_path"],
            "--json", r["report_json_path"],
        ],
        capture_output=True,
        text=True,
    )
    dt = time.time() - t0
    if result.returncode == 0:
        print(f"OK {tag} ({dt:.1f}s)", flush=True)
    else:
        print(f"FAILED {tag} ({dt:.1f}s)", flush=True)
        print(result.stdout[-2000:], flush=True)
        print(result.stderr[-2000:], flush=True)

print("=== RECAST-friends ablation backfill done ===", flush=True)
